"""Criar tabela marcador

Revision ID: 70ef1528af10
Revises: 0dae89413f98
Create Date: 2025-02-24 07:31:05.464524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ef1528af10'
down_revision: Union[str, None] = '0dae89413f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcadores_descricao'), 'marcadores', ['descricao'], unique=False)
    op.create_index(op.f('ix_marcadores_id'), 'marcadores', ['id'], unique=False)
    op.create_index(op.f('ix_marcadores_latitude'), 'marcadores', ['latitude'], unique=False)
    op.create_index(op.f('ix_marcadores_longitude'), 'marcadores', ['longitude'], unique=False)
    op.create_index(op.f('ix_marcadores_titulo'), 'marcadores', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marcadores_titulo'), table_name='marcadores')
    op.drop_index(op.f('ix_marcadores_longitude'), table_name='marcadores')
    op.drop_index(op.f('ix_marcadores_latitude'), table_name='marcadores')
    op.drop_index(op.f('ix_marcadores_id'), table_name='marcadores')
    op.drop_index(op.f('ix_marcadores_descricao'), table_name='marcadores')
    op.drop_table('marcadores')
    # ### end Alembic commands ###
